### PR TITLE
kselftest: Modifying test case names to match pattern

### PR DESCRIPTION
**Pull request by nareshkamboju**
Signed-off-by: Naresh Kamboju <naresh.kamboju@linaro.org>

### CODE REVIEW

**Comment by chaws** [comment]
I have checked the changes and they seem OK

There is only one important consequence by syncing these changes: since you are changing all known issues in kselftest-production.yaml, the script detects that there are extra known issues in squad that no longer exist in the yaml file. The script will ask SQUAD to remove all these extra known issues and will create new ones. The problem with deleting old ones is that all previous tests will detach from them. You might see some extra false-positive regressions in the next build or so. 

The new known issues will only affect new tests.

Is that ok with you?

**Comment by nareshkamboju** [comment]
@chaws I understand the changes. Let this get merged.

**Comment by chaws** [comment]
OK, merging now. Will keep an eye on this

**Comment by chaws** [comment]
@nareshkamboju Syinced this about an hour ago

**Pull request merged**
